package com.springboot.controller;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.springboot.model.User;
import com.springboot.repository.UserRepository;

@RestController
@RequestMapping(path="/demo", method = {RequestMethod.GET,RequestMethod.POST,RequestMethod.PUT, RequestMethod.DELETE})
public class MainController {

  // This means to get the bean called userRepository,Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam("name") String name
      , @RequestParam("email") String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(name);
    n.setEmail(email);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
  
  @GetMapping("/find/{id}")
  public @ResponseBody User getUser(@PathVariable("id") Integer userid) {
	  Optional<User> userObj = userRepository.findById(userid);
	  return userObj.get();
	  
  }
 
  @PutMapping("/update")
  public @ResponseBody String upadateUser(@RequestParam("id") Integer userid,
		  @RequestParam(value="name", required = false) String name, @RequestParam(value="email",required = false) String email) {
	  Optional<User> userObj = userRepository.findById(userid);
	  userObj.get().setName(name);
	  userObj.get().setEmail(email);
	  userRepository.save(userObj.get());
	  return "Updted";
	  
  }
  
  
  @DeleteMapping("/delete/{id}")
  public @ResponseBody String deleteUser(@PathVariable("id") Integer userid) {
	  userRepository.deleteById(userid);
	  return "Deleted";
	  
  }
}
