spring.application.name=jwt-service-communication
server.port=8081

# JWT Auth Service URL
auth.service.url=http://localhost:8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.bs=DEBUG
