spring:
  application:
    name: spring-ai-project
  datasource:
      url: jdbc:postgresql://localhost:5432/ai_db
      username: postgres
      password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
#    openai:
#      api-key: ollama
    vectorstore:
      pgvector:
        initialize-schema: true

